### ISSUE TITLE
Add contributor assigned into Issue in project-Issues page

### ISSUE THREAD

**Issue by sofiaromorales** [setlife-network/trinary#537]
In the issue tile try to:
* Add a small circular image with the contributor is assigned to that issue. The image is not mandatory but is a plus, can be extracted from GitHub using the profile image URL. If it's not possible to use the image then add the name
* On hover change the mouse state so the user knows it's clickable
* on click redirect to the contributor detail page

**Comment by otech47** [comment]
- [ ] Create a Contributions data model + table (`contributor_id`, `issue_id`) to relate Contributors with Issues

Other fields: `is_author=0/1`, `is_assigned=0/1`, `date_created`, `date_updated`

- [ ] Records to be synced in the Contributions will belong to any Contributor that has left at least 1 comment, has created the issue, or has been assigned

consider what happens if a Contributor assigns by mistake then unassigns
